package com.example.list_view

const val MOVIE_TITLE_KEY = "MOVIE_TITLE_KEY"
const val MOVIE_RATING_KEY = "MOVIE_RATING_KEY"
const val MOVIE_IMAGE_KEY = "MOVIE_IMAGE_KEY"
const val MOVIE_LANGUAGE_KEY = "MOVIE_LANGUAGE_KEY"
const val MOVIE_DATE_KEY = "MOVIE_DATE_KEY"
const val MOVIE_OVERVIEW_KEY = "MOVIE_OVERVIEW_KEY"
const val MOVIE_GENRE_KEY = "MOVIE_GENRE_KEY"
